---
title: "Harris_Transformation_Script_Combo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
##Loading Libraries 

```{r}
#setwd(************************)

library(readr)
library(dplyr) 
library(ggplot2)

install.packages('trainControl')
```

## Loading the Dataset 

You can also embed plots, for example:

```{r}

df <- read_csv("Ames_HousePrice.csv")
head(df)
```

## Dealing with Missing Values 

```{r}
df <- df%>% 
  mutate(Alley = ifelse(is.na(Alley) == TRUE, "no_alley", Alley), 
         MasVnrType = ifelse(is.na(MasVnrType) == TRUE, "None", MasVnrType), 
         BsmtQual = ifelse(is.na(BsmtQual) == TRUE, "None", BsmtQual), 
         BsmtCond = ifelse(is.na(BsmtCond) == TRUE, "None", BsmtCond), 
         BsmtExposure = ifelse(is.na(BsmtExposure) == TRUE, "None", BsmtExposure), 
         BsmtFinType1 = ifelse(is.na(BsmtFinType1) == TRUE, "None", BsmtFinType1), 
         BsmtFinType2 = ifelse(is.na(BsmtFinType2) == TRUE, "None", BsmtFinType2), 
         LotFrontage = ifelse(is.na(LotFrontage) == TRUE, 0, LotFrontage), 
         MasVnrArea = ifelse(is.na(MasVnrArea) == TRUE, 0, MasVnrArea), 
         BsmtFinSF1 = ifelse(is.na(BsmtFinSF1) == TRUE, 0, BsmtFinSF1), 
         BsmtFinSF2 = ifelse(is.na(BsmtFinSF2) == TRUE, 0, BsmtFinSF2), 
         BsmtUnfSF = ifelse(is.na(BsmtUnfSF) == TRUE, 0, BsmtUnfSF),
         TotalBsmtSF = ifelse(is.na(TotalBsmtSF) == TRUE, 0, TotalBsmtSF),
         Electrical = ifelse(is.na(Electrical) == TRUE, "SBrkr", Electrical),
         GarageArea = ifelse(is.na(GarageArea) == TRUE, 0, GarageArea),
         BsmtFullBath = ifelse(is.na(BsmtFullBath) == TRUE, 0, BsmtFullBath), 
         BsmtHalfBath = ifelse(is.na(BsmtHalfBath) == TRUE, 0, BsmtHalfBath), 
         FireplaceQu = ifelse(is.na(FireplaceQu) == TRUE, "no_fireplace", FireplaceQu), 
         GarageType = ifelse(is.na(GarageType) == TRUE, "no_garage", GarageType), 
         GarageFinish = ifelse(is.na(GarageFinish) == TRUE, "no_garage", GarageFinish), 
         GarageQual = ifelse(is.na(GarageQual) == TRUE, "no_garage", GarageQual), 
         GarageCond = ifelse(is.na(GarageCond) == TRUE, "no_garage", GarageCond), 
         PoolQC = ifelse(is.na(PoolQC) == TRUE, "no_pool", PoolQC), 
         Fence = ifelse(is.na(Fence) == TRUE, "no_fence", Fence), 
         MiscFeature = ifelse(is.na(MiscFeature) == TRUE, "no_misc", MiscFeature),
         GarageCars = ifelse(is.na(GarageCars) == TRUE, 0, GarageCars)
         )

#imputation of missing garageyrblt values as the same as respective yearbuilt
df$GarageYrBlt <- ifelse(is.na(df$GarageYrBlt), df$YearBuilt, df$GarageYrBlt)

sum(is.na(df))
colSums(is.na(df))

```
```{r}
#playing


```


#Standardizing SalePrice

```{r}
df <- df %>% 
  mutate(stand_scores = abs(SalePrice - mean(SalePrice))/sd(SalePrice)
         )
```
#Converting Variables to Ordinal Factors 

```{r} 
ranks <- c("None", "Po", "Fa", "TA", "Gd", "Ex")
df$BsmtQual <- factor(as.numeric(factor(df$BsmtQual, ranks))) 
df$BsmtCond <- factor(as.numeric(factor(df$BsmtCond, ranks))) 

ranks_ex <- c('None', 'No', 'Mn', 'Av', 'Gd')
df$BsmtExposure <- factor(as.numeric(factor(df$BsmtExposure, ranks_ex)))

ranks_exterior <- c('Po', 'Fa', 'TA', 'Gd', 'Ex')
df$ExterQual <- factor(as.numeric(factor(df$ExterQual, ranks_exterior)))
df$ExterCond <- factor(as.numeric(factor(df$ExterCond, ranks_exterior))) 

ranks_garage <- c("no_garage", "Po", "Fa", "TA", "Gd", "Ex")
df$GarageQual <- factor(as.numeric(factor(df$GarageQual, ranks_garage))) 
df$GarageCond <- factor(as.numeric(factor(df$GarageCond, ranks_garage))) 

ranks_pool <- c("no_pool", "Fa", "TA", "Gd", "Ex")
df$PoolQC <- factor(as.numeric(factor(df$PoolQC, ranks_pool))) 

ranks_3 <- c('Po', 'Fa', 'TA', 'Gd', 'Ex')
df$HeatingQC <- factor(as.numeric(factor(df$HeatingQC, ranks_3)))
df$KitchenQual <- factor(as.numeric(factor(df$KitchenQual, ranks_3))) 

#making orders
ranks_mason <- c('None','BrkCmn', 'BrkFace', 'CBlock', 'Stone') 
df$MasVnrType <- factor(df$MasVnrType, ranks_mason)  

ranks_housestyle <- c('1Story', '1.5Unf', '1.5Fin', '2Story', '2.5Unf', '2.5Fin', 'SFoyer', 'SLvl')  
df$HouseStyle <- factor(df$HouseStyle, ranks_housestyle) 

ranks_bsmttype <- c('None', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ')
df$BsmtFinType1 <- factor(df$BsmtFinType1, ranks_bsmttype) 
df$BsmtFinType2 <- factor(df$BsmtFinType2, ranks_bsmttype)

ranks_fence <- c("no_fence", "MnWw", "GdWo", "MnPrv", "GdPrv")
df$Fence <- factor(df$Fence, ranks_fence) 

ranks_fireplace <- c("no_fireplace", "Po", "Fa", "TA", "Gd", "Ex")
df$FireplaceQu <- factor(df$FireplaceQu, ranks_fireplace)

ranks_functional <- c("Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ")
df$Functional <- factor(df$Functional, ranks_functional)

ranks_garagefinish <- c("no_garage", "Unf", "RFn", "Fin")
df$GarageFinish <- factor(df$GarageFinish, ranks_garagefinish)

ranks_drive <- c("N", "P", "Y")
df$PavedDrive <- factor(df$PavedDrive, ranks_drive)

ranks_saletype <- c("Oth", "ConLD", "ConLI", "ConLw", "Con", "COD", "New", "VWD", "CWD", "WD")
df$SaleType <- factor(df$SaleType, ranks_saletype)

ranks_salecondition <- c("Partial", "Family", "Alloca", "AdjLand", "Abnorml", "Normal")
df$SaleCondition <- factor(df$SaleCondition, ranks_salecondition)

```

#Making the Dummy Variables 

```{r} 

df$MSZoning <- model.matrix(~MSZoning -1, data = df)
df$Street <- model.matrix(~Street -1, data = df)
df$Alley <- model.matrix(~Alley -1, data = df) 
df$LotShape <- model.matrix(~LotShape -1, data = df) 
df$LandContour <- model.matrix(~LandContour -1, data = df) 
df$Utilities <- model.matrix(~Utilities -1, data = df) 
df$LotConfig <- model.matrix(~LotConfig -1, data = df) 
df$LandSlope <- model.matrix(~LandSlope -1, data = df) 
df$Condition1 <- model.matrix(~Condition1 -1, data = df) 
df$Condition2 <- model.matrix(~Condition2 -1, data = df) 
df$BldgType <- model.matrix(~BldgType -1, data = df) 
df$RoofStyle <- model.matrix(~RoofStyle -1, data = df) 
df$RoofMatl <- model.matrix(~RoofMatl -1, data = df) 
df$Exterior1st <- model.matrix(~Exterior1st -1, data = df) 
df$Exterior2nd <- model.matrix(~Exterior2nd -1, data = df) 
df$MasVnrType <- model.matrix(~MasVnrType -1, data = df) 
df$Foundation <- model.matrix(~Foundation -1, data = df) 
df$HouseStyle <- model.matrix(~HouseStyle -1, data = df) 
df$BsmtFinType1 <- model.matrix(~BsmtFinType1 -1, data = df)
df$BsmtFinType2 <- model.matrix(~BsmtFinType2 -1, data = df)
df$Heating <- model.matrix(~Heating -1, data = df)
df$HeatingQC <- model.matrix(~HeatingQC -1, data = df)
df$Electrical <- model.matrix(~Electrical -1, data = df) 
df$KitchenQual <- model.matrix(~KitchenQual -1, data = df) 
df$Functional <- model.matrix(~Functional -1, data = df) 
df$FireplaceQu <- model.matrix(~FireplaceQu -1, data = df) 
df$GarageType <- model.matrix(~GarageType -1, data = df) 
df$GarageFinish <- model.matrix(~GarageFinish -1, data = df) 
df$GarageQual <- model.matrix(~GarageQual -1, data = df) 
df$GarageCond <- model.matrix(~GarageCond -1, data = df) 
df$PavedDrive <- model.matrix(~PavedDrive -1, data = df) 
df$PoolQC <- model.matrix(~PoolQC -1, data = df) 
df$Fence <- model.matrix(~Fence -1, data = df) 
df$MiscFeature <- model.matrix(~MiscFeature -1, data = df) 
df$SaleType <- model.matrix(~SaleType -1, data = df) 
df$SaleCondition <- model.matrix(~SaleCondition -1, data = df) 
df$CentralAir <- model.matrix(~CentralAir -1, data = df) 
df$Neighborhood <- model.matrix(~Neighborhood -1, data = df)

```

#removing outliers  
```{r} 
df1 <- df %>% 
  filter(stand_scores < 3 & LotArea < 25000)

df2 <- df1 %>% 
  dplyr::select(-PID, -X1, -GrLivArea, -stand_scores, -GarageCars, -BedroomAbvGr, -KitchenAbvGr, -MSSubClass, -MSZoning, -LotFrontage, -LotShape, -LandContour, -BldgType, -OverallQual, -OverallCond, -Heating, -TotRmsAbvGrd, -SaleType, -SaleCondition, -LotConfig)



```
#scaling the area and square footage 
```{r}

#renaming cols with numbers so that dplyr will work
names(df2)[names(df2) == "1stFlrSF"] <- "X1stFlrSF"
names(df2)[names(df2) == "2ndFlrSF"] <- "X2ndFlrSF"
names(df2)[names(df2) == "3SsnPorch"] <- "X3SsnPorch"

df3 <- df2 %>% 
  mutate(MasVnrArea = log(MasVnrArea + 1), 
         BsmtFinSF1 = log(BsmtFinSF1 + 1), 
         BsmtFinSF2 = log(BsmtFinSF2 + 1), 
         BsmtUnfSF = log(BsmtUnfSF + 1),
         LotArea = log(LotArea + 1),
         X1stFlrSF = log(X1stFlrSF + 1), 
         X2ndFlrSF = log(X2ndFlrSF + 1), 
         GarageArea = log(GarageArea + 1),
         WoodDeckSF = log(WoodDeckSF + 1),
         OpenPorchSF = log(OpenPorchSF + 1),
         EnclosedPorch = log(EnclosedPorch + 1),
         X3SsnPorch = log(X3SsnPorch + 1),
         ScreenPorch = log(ScreenPorch + 1),
         PoolArea = log(PoolArea + 1))


```
#checking if works in a linear model 
```{r} 
df_null <- lm(log(SalePrice) ~ LotArea, data = df3)

df_full <- lm(log(SalePrice) ~ LotArea + Street +
    Alley + Utilities + Condition1 + Condition2 + HouseStyle + RoofStyle +
    RoofMatl + Exterior1st + Exterior2nd + MasVnrType + MasVnrArea +
    ExterQual + ExterCond + Foundation + BsmtQual + BsmtCond +
    BsmtExposure + BsmtFinType1 + BsmtFinSF1 + BsmtFinType2 +
    BsmtFinSF2 + BsmtUnfSF + Neighborhood + HeatingQC + CentralAir + Electrical + X1stFlrSF +
    X2ndFlrSF + LowQualFinSF + BsmtFullBath + FullBath + HalfBath +
    KitchenQual + Functional + Fireplaces + FireplaceQu +
    GarageType + GarageYrBlt + GarageFinish +
    GarageArea + GarageQual + GarageCond + PavedDrive + WoodDeckSF +
    OpenPorchSF + EnclosedPorch + X3SsnPorch + ScreenPorch + PoolArea +
    Fence + MiscFeature + MiscVal + MoSold +
    YrSold, data = df3)

step_BIC3 <- step(df_full, k = log(2500))

step_BIC4 <- step(df_null, scope = list(lower = df_null, upper = df_full), direction = 'both', k = log(2500))

summary(step_BIC3)
```


```{r}
set.seed(1212)

index = sample(1:nrow(df3), size = nrow(df3)*0.8)

train_data = df3[index, ]
test_data = df3[-index, ]
tune.grid = expand.grid(lambda = (0:10)*0.1, alpha=0)
ctrl = trainControl(method = "repeatedcv", number = 5, repeats = 5)
logit_shrinkage = train(default ~ ., data=train_data,
 method = "glmnet", metric = "Accuracy",
 preProc=c('center', 'scale'),
 trControl = ctrl, tuneGrid = tune.grid)


```